### ISSUE TITLE
Some downloads are saved without file extention

### ISSUE THREAD

**Issue by alexanderadam** [mediathekview/zapp#172] opened 2019-09-30 07:04 UTC
I downloaded some video (I think it was some `Planet Wissen` movie from WDR/ARD) and Android didn't wanted to handle the file because it had no file extension.

Maybe it would make sense to add a default file extension (maybe `….mp4`?) so that it wouldn't require to rename a file (I'm not even sure whether renaming is generally possible with onboard tools in Android).

**Comment by cemrich** [comment] 2019-10-02 10:19
@alexanderadam I cannot reproduce this bug. Do you remember the exact show that caused the error?

**Comment by alexanderadam** [comment] 2019-10-02 11:20
@cemrich Actually a lot of "Planet Wissen" videos are affected (probably more).
For example when I search for "Planet Wissen" right now, there's a new video called "Was ist das Pferd eigentlich für ein Tier?" from ARD. When I tap now on the download button of "Low" quality, the resulting video doesn't have any extension.
I can play it in the view from the Download Manager app (I guess because it still knows the MIME type from the just downloaded file) but I can't open it from a file manager for example.

**Comment by cemrich** [comment] 2019-10-02 12:08
@alexanderadam Thank you, I can reproduce the issue.

For future reference: There seems to be an error with the construction of the [download file name](https://github.com/mediathekview/zapp/blob/4361a3f9dd8f09f261bd30b5cd579d8cc206b270/app/src/main/java/de/christinecoenen/code/zapp/app/mediathek/model/MediathekShow.java#L241).

**Comment by cemrich** [comment] 2019-10-03 18:30
Got it! The question mark at the end of the title is causing this problem. File name sanitation has to be way better than now.

**Comment by cemrich** [comment] 2020-01-15 09:59
This issue is fixed in v3.3.0, which will hit F-Droid in a few days. Please reopen this issue if you find any problems.

**Closed by cemrich** 2020-01-15 09:59 UTC
Labels: bug, fixed in next release ✓
