### ISSUE TITLE
[7.0.1] Playback stops (screen goes black) after 20 minutes of watching a channel

### ISSUE THREAD

**Issue by sbellon** [mediathekview/zapp#300] opened 2022-06-09 05:36 UTC
Preface: I can report that Zapp 7.0.1 now starts properly on the Fire TV with the new TV UI.

But I noticed that when watching a channel, the screen goes black (and audio stops as well) 20 minutes after the last interaction. The first keypress "OK" then brings back the paused screen, second keypress "OK" shows the timeline and the play button, third keypress "OK" resumes playback.

This repeats 20 minutes later again, etc. I tried it on different channels to make sure it's not some channel related behaviour.

Any idea what this is? Some kind of screensaver? This does not occur on the same Fire TV device with Zapp 6.0.2 installed.

**Comment by coding-pivo** [comment] 2022-06-16 08:15
I can confirm the very same behavior on each of my Fire TV Sticks with version 7.02. Version 6.0.1 was working properly and now I get the Amazon screensaver every 20 minutes.

**Comment by cemrich** [comment] 2022-06-16 10:31
Thank you very much for your report!

I have to evaluate this, but it might an duplicate of https://github.com/mediathekview/zapp/issues/293

**Comment by cemrich** [comment] 2022-06-16 10:50
I can reproduce this issue on an standard Android emulator. For some reason the player does not grap a screen lock.

**Comment by cemrich** [comment] 2022-06-16 14:14
By bad - I forgot to keep the screen on during playback on Android TV devices. This should be fixed in the next release.

**Comment by sbellon** [comment] 2022-06-18 08:42
Version 7.0.3 now works perfectly fine on my Fire TV. Thanks a lot. :-)

**Comment by cemrich** [comment] 2022-06-18 09:14
> Version 7.0.3 now works perfectly fine on my Fire TV. Thanks a lot. :-)

Nice! Thank you for testing :)

**Closed by cemrich** 2022-06-18 09:14 UTC
Labels: bug, fixed in next release ✓
