### ISSUE TITLE
Wrong filename / Zapp downloads file as `downloadfile`

### ISSUE THREAD

**Issue by alexanderadam** [mediathekview/zapp#183] opened 2020-03-04 08:32 UTC
Hi @cemrich, sorry for bothering you again but I found another filename bug.

Search for [`Künstliche Intelligenz - Herrschaft der Maschinen? - Richard David Precht im Gespräch mit Prof. Jürgen Schmidhuber, Informatiker und KI-Pionier`](https://www.zdf.de/gesellschaft/precht/precht-206.html) and try to download it in medium quality.

The resulting filename is just `downloadfile` without any extension.

**Comment by cemrich** [comment] 2020-03-05 18:56
This is what an issue tracker is here for :)

It works on my machine though... Which version of Android are you using?

**Comment by alexanderadam** [comment] 2020-03-06 07:33
> It works on my machine though...

Which of the two publications did you try? The one from 3Sat is working for me as well. Only the one from ZDF is causing this. (which is the one I linked here as well).

> Which version of Android are you using?

Samsung Tablet S4 with One UI `1.1` and Android `9` (Kernel `4.4.153-1709687`, Build `PPR1.180610.011.T835XXU4BSJ6`, Patch level `01. November 2019`).

**Comment by cemrich** [comment] 2020-03-06 19:25
Still can't reproduce this on my Android 9 (Lineage) device. I will test on some more devices / emulators.

**Comment by cemrich** [comment] 2020-03-06 19:48
The emulator with stock Android works just fine. But another Samsung phone shows the same behavior. I think this might be a bug / restriction of the Samsung download manager. I'll try to cut special characters / title length until it does not complain any more.

**Comment by cemrich** [comment] 2020-04-04 12:08
File names for Samsung download manager have to be restricted to 120 characters for whatever reason...

**Comment by rugk** [comment] 2020-04-07 21:07
Samsung™ :rofl:

**Comment by cemrich** [comment] 2020-05-01 08:59
This issue should be fixed in release [v3.4.0](https://github.com/mediathekview/zapp/releases/tag/v3.4.0) which should hit F-Droid the next few days.

**Closed by cemrich** 2020-05-01 08:59 UTC
Labels: bug, fixed in next release ✓
