### ISSUE TITLE
Download aborts on screen lock

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#311] opened 2022-07-16 05:00 UTC
**Device**: Samsung Galaxy XCover 4s
**OS**: Android 11
**App**: 7.03

**Comment by WebworkrNet** [comment] 2022-07-16 05:01
Related to #261.

**Comment by WebworkrNet** [comment] 2022-07-16 05:03
Related to #224.

**Comment by WebworkrNet** [comment] 2022-07-25 13:08
An exception is when a live stream is playing in the background at the same time and the screen is then locked by the system (#241). 
Then the error does not occur.

**Comment by cemrich** [comment] 2022-08-03 12:45
Duplicate of #224

**Closed by cemrich** 2022-08-03 12:45 UTC
