### ISSUE TITLE
Popup windows don't respect system animation speed on android 8

### ISSUE THREAD

**Issue by SebiderSushi** [mediathekview/zapp#374] opened 2023-07-25 18:32 UTC
### Problem summary
Popup windows don't respect the window animation speed system setting, at least on android 8.1.0

### Reproduction environment
App version: 8.3.1 from F-Droid
Android version: LineageOS 15.1 (android 8.1.0)

### Steps to reproduce
1. Change window animation speed
    - [On any android version] Enable development settings and change the setting "Window animation scale"
    - [On android 11] Go to Settings > Accessibility and turn on "Remove animations"
2. Install Zapp 8.2.0
3. Open Zapp
4. Go to Settings
5. Tap any multiple choice setting (e.g. Theme, Start page, Language) or go to "Channel order" and click the question mark icon in the title bar
6. On the "Media Center" tab, open any entry, then click "Download" or "Share"
7. While playing a live stream, tap on the "info" or "sleep timer" icon in the top right corner
8. Upgrade to Zapp 8.3.1 and repeat

### Expected behavior
The window opens with the appriopriate animation speed as set in system settings.

### Observed behavior
 - LineageOS 15.1 (android 8.1.0), Zapp version 8.2.0
   Window animation speed corresponds with system setting
   The live stream info card does not react to system animation speed but the animation is fairly short.
 - LineageOS 15.1 (android 8.1.0), Zapp version 8.3.1
   Window animation speed does not change even when all of the three animation scale system settings are changed.
   The closing animation of the live stream info card corresponds to the system animation speed.
 - LineageOS 18.1 (android 11), Zapp version 8.2.0
   Window animation speed corresponds with system setting
 - LineageOS 18.1 (android 11), Zapp version 8.3.1
   Window animation speed corresponds with system setting

Those were all versions i tested. I don't know which android version is the precise cut-off for this problem.

**Comment by cemrich** [comment] 2023-07-26 13:20
Thank you very much for your feedback!

I cannot reproduce this behaviour on Stock Android 10 or 13.
Stock Android 8.0 does not provide this system setting.

However, Zapp does not use any fancy components - just `MaterialAlertDialogBuilder`, which should respect all system settings by default. I supsect this to be a bug in [Androids material library](https://github.com/material-components/material-components-android/issues). Or, it could be a some custom implementation of early lineage versions.

I don't think this issue is something that can be fixed inside Zapp, I am sorry!

**Closed by cemrich** 2023-07-26 13:20 UTC
