### ISSUE TITLE
Merge duplicates (same channel)

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#279] opened 2022-03-09 04:21 UTC
Duplicates appear in the list of available programmes. Unlike #228, however, I am referring to identical programmes on the same channel.

Example:
MaiThink X - Die Show - Sternstunden der Neolution - Teil 1
`https://rodlzdf-a.akamaihd.net/none/zdf/21/10/211004_neolution_mai/2/211004_neolution_mai_3360k_p36v15.mp4`

- Mediathekviewweb 1x listed.
- Zapp 2x listed.

**Comment by WebworkrNet** [comment] 2022-03-09 04:26
Another example:
MaiThink X - Die Show	
Kritisches Denken - mit Lutz van der Horst & Fabian Köster
`https://rodlzdf-a.akamaihd.net/none/zdf/21/10/211022_kritisches_denken4_mai/1/211022_kritisches_denken4_mai_3360k_p36v15.mp4`

- Mediathekviewweb 1x listed.
- Zapp 2x listed.

**Comment by strelitzer** [comment] 2022-03-12 16:13
I can only find/see both programs once in Zapp.

**Comment by cemrich** [comment] 2022-03-16 19:09
I can't reproduce this issue either.

**Comment by cemrich** [comment] 2022-10-23 11:49
I'll close this for now. Feel free to open a new issue if this ever happens again.

**Closed by cemrich** 2022-10-23 11:49 UTC
Labels: triage

**Comment by cemrich** [comment] 2024-04-14 09:47
This is an old one, but I could reproduce this issue and fixed it. There was an issue with the paging keys, so some entries (number 60 to 90 in the list) were loaded two times.
