### ISSUE TITLE
App crash with playback in background

### ISSUE THREAD

**Issue by gweax** [mediathekview/zapp#215] opened 2020-10-30 19:05 UTC
The app crashes repeatable following these steps:

1. Open the app.
2. From the list of live tv channels select any.
3. Switch to playback in background ("Im Hintergrund abspielen").
4. Now the list of channels is in the foreground. Tap on any channel.
5. The app crashes.

Attached is the error report generated by the app.

```
REPORT_ID=c0507566-977a-44a1-bf4d-a8d6a2938ff2
USER_EMAIL=
USER_COMMENT=
IS_SILENT=false
USER_CRASH_DATE=2020-10-30T19:45:21.148+01:00
APP_VERSION_NAME=3.6.0
APP_VERSION_CODE=46
ANDROID_VERSION=11
PHONE_MODEL=Pixel 2
BRAND=google
SHARED_PREFERENCES=default.pref_wifi_only=true
default.pref_ui_mode=0
default.pref_detail_landscape=false
default.pref_download_wifi_only=true
default.pref_shortcuts=["zdf_neo","das_erste","one","zdf"]
default.pref_key_player_zoomed=false
default.pref_enable_subtitles=false
default.acra.legacyAlreadyConvertedTo4.8.0=true
default.acra.legacyAlreadyConvertedToJson=true
default.pref_key_download_to_sd_card=true
default.acra.lastVersionNr=46
default.pref_key_stream_quality_cellular=lowest
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String de.christinecoenen.code.zapp.b.a.d()' on a null object reference
at de.christinecoenen.code.zapp.app.livestream.ui.detail.ChannelDetailActivity$a.a(ChannelDetailActivity.java:2)
at de.christinecoenen.code.zapp.app.livestream.ui.detail.ChannelDetailActivity$c.onServiceConnected(ChannelDetailActivity.java:10)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1954)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1986)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by cemrich** [comment] 2020-10-30 19:08
Thanks for the bug report! Due to this covid childcare situation this may take some time to fix.

**Comment by gweax** [comment] 2020-10-30 19:13
Actually, I only encountered this bug because I accidentally tapped on "Im Hintergrund abspielen" where I really wanted to activate "Bild im Bild". So from my side there's no need to hurry :-)

Have a nice weekend with the kid(s)!

**Comment by giwu37** [comment] 2020-10-30 21:41
I cant reproduce this. Works with no crash for me.

Am 30. Oktober 2020 20:13:56 MEZ schrieb Matthias Reuter <notifications@github.com>:
>Actually, I only encountered this bug because I accidentally tapped on "Im Hintergrund abspielen" where I really wanted to activate "Bild im Bild". So from my side there's no need to hurry :-)
>
>Have a nice weekend with the kid(s)!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mediathekview/zapp/issues/215#issuecomment-719745750
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by cemrich** [comment] 2020-12-18 20:01
I can't reproduce this either. But I get crash reports for this error for Android versions 9 through 11.

Maybe it is some kind of timing bug or performance related...

**Comment by gweax** [comment] 2020-12-19 19:32
I retested this just now (with Zapp version 3.6.1) and cannot reproduce it anymore.

**Comment by cemrich** [comment] 2020-12-20 14:33
> I retested this just now (with Zapp version 3.6.1) and cannot reproduce it anymore.

Thank you for testing again! Have you used the same device as last time? I still suspect some timing issue, but I'll close this issue when nobody is able to reproduce it :(

**Comment by cemrich** [comment] 2021-10-02 18:03
Feel free to reopen if this is still an issue.

**Closed by cemrich** 2021-10-02 18:03 UTC
Labels: bug, triage
