### ISSUE TITLE
Create playlist

### ISSUE THREAD

**Issue by seyfeb** [mediathekview/zapp#180] opened 2020-01-30 19:02 UTC
Currently, every time one wants to continue watching a series, one has to search again and scroll through the results list to find the relevant videos.
If there are complete seasons of a TV show released, it would be nice to collect them in some kind of playlist. Best case would certainly be automatically, but also adding them manually, e.g., from the search results would be nice.

**Comment by cemrich** [comment] 2020-01-31 12:40
Thank you for your suggestion!
This is a duplicate of #143 and #176

**Closed by cemrich** 2020-01-31 12:40 UTC
Labels: enhancement

**Comment by seyfeb** [comment] 2020-01-31 13:36
I saw #176, but since subscribing to a future releases of a show is not possible, I suggested creating a simple list, were you add items manually. Like: Select multiple items in the search results and click on “create playlist”, or “collection” or something similar. 
#143 I didn‘t see, but this is probably more in the same direction (although with favorites you would only be able to maintain a single list)

**Comment by cemrich** [comment] 2020-02-04 16:30
Yes, your feature would be a combination of both. I think managing multiple lists would be quite challenging for most users as it would complicate the user interface. Anyway, I have to wait for MedithekViewWeb Api 2.0 to implement this or similar features in a clean manner.
