### ISSUE TITLE
Add SRF to live tv

### ISSUE THREAD

**Issue by Mannshoch** [mediathekview/zapp#217] opened 2020-12-05 08:38 UTC
Please add SRF Tv to the live section. May only show it if channel is reachable (User in Switzerland)

https://www.srf.ch/play/tv/live

**Comment by cemrich** [comment] 2020-12-05 13:11
Thank you very much for your feedback!

This is a duplicate of #2 and currently out of scope. I am very sorry.

**Closed by cemrich** 2020-12-05 13:11 UTC
Labels: duplicate
