### ISSUE TITLE
App crashes on launch (fixed after uninstall/reinstall)

### ISSUE THREAD

**Issue by Der-Flip** [mediathekview/zapp#372] opened 2023-07-23 18:17 UTC
App crashes immediately when launched, this is the crash report

```
REPORT_ID=ff086093-5938-4fef-b4a5-944f4a03124e
USER_EMAIL=
USER_COMMENT=
IS_SILENT=false
USER_CRASH_DATE=2023-07-23T20:08:53.315+02:00
APP_VERSION_NAME=8.3.0
APP_VERSION_CODE=66
ANDROID_VERSION=10
PHONE_MODEL=M2006C3MG
BRAND=Redmi
SHARED_PREFERENCES=default.pref_key_player_zoomed=false
	default.pref_ui_mode=dark
	default.pref_detail_landscape=true
	default.dynamic_colors=false
	default.pref_key_pip_on_back=false
	default.pref_key_language=de
	default.pref_download_wifi_only=false
	default.pref_shortcuts=[]
	default.pref_key_download_to_sd_card=true
	default.pref_key_stream_quality_cellular=highest
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{de.christinecoenen.code.zapp/de.christinecoenen.code.zapp.app.main.MainActivity}: android.view.InflateException: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3340)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
Caused by: android.view.InflateException: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #40 in de.christinecoenen.code.zapp:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
	at w6.a.<init>(SourceFile:10)
	at m8.b.<init>(Unknown Source:0)
	at m8.c.a(Unknown Source:16)
	at m8.a.a(Unknown Source:9)
	at r8.c.d(Unknown Source:12)
	at r8.b.<init>(Unknown Source:21)
	at r8.c.<init>(Unknown Source:0)
	at de.christinecoenen.code.zapp.app.livestream.ui.list.ChannelListFragment.L(Unknown Source:9)
	at androidx.fragment.app.z0.e(Unknown Source:65)
	at androidx.fragment.app.z0.k(Unknown Source:150)
	at androidx.fragment.app.r0.z(Unknown Source:1044)
	at androidx.fragment.app.r0.U(Unknown Source:91)
	at androidx.fragment.app.r0.x(Unknown Source:73)
	at androidx.fragment.app.r0.t(Unknown Source:64)
	at androidx.fragment.app.w.L(Unknown Source:51)
	at androidx.navigation.fragment.NavHostFragment.L(Unknown Source:553)
	at androidx.fragment.app.z0.e(Unknown Source:65)
	at androidx.fragment.app.z0.k(Unknown Source:150)
	at androidx.fragment.app.r0.z(Unknown Source:1044)
	at androidx.fragment.app.r0.U(Unknown Source:91)
	at androidx.fragment.app.r0.y(Unknown Source:31)
	at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:43)
	at androidx.fragment.app.e0.onCreateView(SourceFile:3)
	at androidx.fragment.app.z.onCreateView(SourceFile:4)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1088)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1144)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1147)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at de.christinecoenen.code.zapp.app.main.MainActivity.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3315)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

**Comment by Der-Flip** [comment] 2023-07-23 18:20
Reinstall apparently fixed it...

**Comment by cemrich** [comment] 2023-07-23 18:37
Thanks for reporting!

This is a duplicate of #371 and fixed in v3.8.1, which hopefully will hit F-Droid in a few days.

**Closed by cemrich** 2023-07-23 18:37 UTC

**Comment by Der-Flip** [comment] 2023-07-23 18:39
Apologies. I checked the issues page but GitHub was a bit of a diva apparently not displaying new issues...

**Comment by WebworkrNet** [comment] 2023-07-24 22:56
@cemrich Can I install the update from GitHub if the app was originally downloaded from F-Droid? With some apps, there are problems with such a procedure. I think file signature is the right keyword in this context.

Thanks
