### ISSUE TITLE
Unlocked screen / background playback: (live) streaming stops.

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp#384] opened 2023-11-04 13:04 UTC
**Device**: Samsung Galaxy A13 5G (SM-A136B/DSN)
**Operating System**: Android 13

The screen is **un**locked.

Without the snooze function (https://github.com/mediathekview/zapp/issues/194) activated, playback occasionally stops after a while without resuming.

Related to question https://github.com/mediathekview/zapp/issues/241.

Related to  #74, #148, #273 and  **especially #383.**

**Comment by WebworkrNet** [comment] 2023-11-07 17:50
Active downloads and queued downloads during backround playback presumably prevent this unwanted behavior.

**Comment by cemrich** [comment] 2023-12-21 10:20
Do you see an error message (notification) after the stream has stopped?

**Comment by WebworkrNet** [comment] 2024-01-29 05:59
The error still occurs:

**Device**: Samsung Galaxy A13 5G (SM-A136B/DSN)
**Operating System**: Android 14, One-UI 6.0

The stream stops unexpectedly without an error message.

**Comment by WebworkrNet** [comment] 2024-01-29 06:08
> Thanks for reporting!
> 
> Is this only an issue with live streaming or with mediathek shows too? Do you play back in background or with the video on screen?

As far as I remember, it only affects live streaming. The phenomenon only occurs with background playback (i.e. no image visible, only sound).

**Comment by WebworkrNet** [comment] 2024-01-29 10:15
Could temporary overheating of the device be the cause?

If this is the case, can this be prevented by a timely notification, but at the latest after the end of the stream with an error message?

**Comment by cemrich** [comment] 2024-02-04 12:38
I suspect aggresive Android power optimization as the main cause. I can reproduce this issue reliably by activating "Restricted battery usage" on stock Android.

@WebworkrNet Can you please check your energy settings for Zapp?

**Comment by WebworkrNet** [comment] 2024-02-04 18:46
I've now changed the settings from "optimized" (probably the default setting on Android) to "unrestricted" and will keep an eye on it.

![Screenshot_20240204_193834_Settings.jpg](https://github.com/mediathekview/zapp/assets/43509007/af0d4e8b-e1ee-4cf5-9f94-61fc02eb13c6)

![Screenshot_20240204_193846_Settings.jpg](https://github.com/mediathekview/zapp/assets/43509007/e84efda3-3a50-4c98-bac2-7fa8f5622087)

**Comment by cemrich** [comment] 2024-02-06 11:33
Funny, "optimized" works fine on my device. Maybe it's device specific.
Thanks for testing!

**Comment by WebworkrNet** [comment] 2024-02-16 15:26
So far I haven't noticed any improvement after adjusting the battery settings. My suspicion of temporary device overheating is confirmed by further observations.

**Comment by cemrich** [comment] 2024-02-20 17:47
Thanks for investigating. As this seems to be a very device specific bug, that cannot be fixed by Zapp, I'll close this issue. Feel free to open a new one if you're seeing buggy behaviour again.

**Closed by cemrich** 2024-02-20 17:47 UTC
Labels: feedback needed

**Comment by WebworkrNet** [comment] 2024-02-29 21:25
The stream also stops if the ad blocker used crashes. As usual, the app uses the VPN interface to control network traffic. Otherwise, this would not be possible if the Android device is not rooted. It is understandable that the data stream stops. In this case, the ZAPP app does not rebuild the video stream. I'll have to check again whether this is true in every case or only occurs intermittently.
